import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex flex-col min-h-screen">
                <header className="h-100 bg-yellow-500 flex items-center justify-center">
                  Header
                </header>
                <div className="h-400">
                {children}
                </div>
                <footer className="flex-shrink-0 h-100 bg-yellow-500 flex items-center justify-center">
                  Footer
                </footer>
            </body>
        </html>
    );
}
